# Generated by Django 3.2.9 on 2021-11-30 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Group name')),
                ('description', models.CharField(max_length=300, verbose_name='Description of group')),
            ],
            options={
                'verbose_name': 'group',
                'verbose_name_plural': 'groups',
                'db_table': 'Groups',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='User nickname')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'Users',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UsersGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.users')),
            ],
            options={
                'db_table': 'Users group',
                'unique_together': {('user', 'group')},
                'index_together': {('user', 'group')},
            },
        ),
    ]
