# Generated by Django 3.2.9 on 2021-11-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='user',
            field=models.ManyToManyField(through='users_app.UsersGroups', to='users_app.Users'),
        ),
    ]
