# Generated by Django 3.2.9 on 2021-11-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_groups_user'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='usersgroups',
            index_together=set(),
        ),
    ]
