# Generated by Django 3.2.9 on 2021-12-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_auto_20211130_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='group',
            field=models.ManyToManyField(through='users_app.UsersGroups', to='users_app.Groups'),
        ),
    ]
